Add prometheus-emitter docs
apache/druid pull request #11618
Opened 2021-08-19 09:06 UTC by jp707049

The `prometheus-emitter` documentation is missing from the druid website. This PR fixes the issue.

This PR has:
- [x] been self-reviewed.

2021-08-23 19:03 UTC, techdocsmith requested changes
Some style edits.

2021-08-23 19:03 UTC, techdocsmith commented on docs/development/extensions.md
> +|prometheus-emitter|This extension exposes [Druid metrics](https://druid.apache.org/docs/latest/operations/metrics.html) for collection by a Prometheus server (https://prometheus.io/)|[link](../devel
```suggestion
|prometheus-emitter|Exposes [Druid metrics](../operations/metrics.md) for Prometheus server collection (https://prometheus.io/)|[link](./extensions-contrib/prometheus.md)|
```
update to relative link style.

2021-08-24 03:44 UTC, jp707049 commented
@techdocsmith updated according to your comments.

2021-08-24 15:46 UTC, techdocsmith approved these changes
LGTM

2021-08-24 15:48 UTC, merged