Docs: Add multi-dimension partitioning doc; refactor native batch and separate into smaller topics.
apache/druid pull request #11983
Opened 2021-11-23 23:12 UTC by techdocsmith

Adds documentation for multi-dimension partitioning. cc: @kfaraz 
Refactors the native batch partitioning topic as follows:
- Native batch ingestion covers `parallel-index`
- Native batch simple task indexing covers `index`
- Native batch input sources covers `ioSource`
- Native batch ingestion with firehose covers deprecated firehose

This PR has:
- [ x] been self-reviewed.

2021-11-24 18:11 UTC, sthetland requested changes
Really happy to see this page getting split up.. Some suggestions and comments, but all in all, nice one!

2021-11-24 18:11 UTC, sthetland commented on docs/ingestion/native-batch.md
> +For segment pruning to be effective and translate into better query performance, you must the first of your `partitionDimensions` at query time. For example, given the following `partitionDimensions`
I think a word(s) is missing here, but not sure what it should be:  "...you must __ the first..."

2021-11-24 18:11 UTC, sthetland commented on docs/ingestion/native-batch.md
> +To enable bulk pushing mode, set `forceGuaranteedRollup` in your TuningConfig. You can not use bulk pushing with `appendToExisting` in your IOConfig.
```suggestion
To enable bulk pushing mode, set `forceGuaranteedRollup` in your TuningConfig. You cannot use bulk pushing with `appendToExisting` in your IOConfig.
```

2021-11-29 08:56 UTC, kfaraz reviewed
Thanks for organizing the docs better, @techdocsmith !
Just one minor comment, otherwise LGTM.

2021-12-01 12:24 UTC, kfaraz approved these changes
LGTM 🚀

2021-12-03 02:16 UTC, sthetland approved these changes

2021-12-03 11:07 UTC, merged

2021-12-07 02:17 UTC, loquisgon commented
LGTM