Addition to Multitenancy considerations doc
apache/druid pull request #12567
Opened 2022-05-25 13:08 UTC by jill-imply

Small addition to Multitenancy considerations doc
This PR has:
- [x] been self-reviewed.

2022-05-25 22:27 UTC, techdocsmith requested changes
minor changes for style

2022-05-25 22:27 UTC, techdocsmith commented on docs/querying/multitenancy.md
> +Druid's fundamental unit of computation is a [segment](../design/segments.md). Processes scan segments in parallel and a given process can scan `druid.processing.numThreads` concurrently. To process
```suggestion
Druid's fundamental unit of computation is a [segment](../design/segments.md). Processes scan segments in parallel and a given process can scan `druid.processing.numThreads` concurrently. You can add more cores to a cluster to process more data in parallel and increase performance. Size your Druid segments such that any computation over any given segment should complete in at most 500ms. Use the  the [`query/segment/time`](../operations/metrics.md#historical) metric to monitor computation times.
```

2022-05-27 04:07 UTC, kfaraz commented on docs/querying/multitenancy.md
> +Druid's fundamental unit of computation is a [segment](../design/segments.md). Processes scan segments in parallel and a given process can scan `druid.processing.numThreads` concurrently. To process
Nit: are we using the possessive case with `Druid` elsewhere, @techdocsmith ?

Maybe we could fix this up too. e.g.
`In Druid, the fundamental unit of computation is a segment`
or
`Druid uses a segment as the fundamental unit of computation`
or something to that effect.

2022-05-30 10:31 UTC, jill-imply commented
Made changes suggested by @kfaraz and @techdocsmith - ready for re-review.

2022-05-31 15:10 UTC, techdocsmith approved these changes
LGTM

2022-06-02 09:40 UTC, kfaraz approved these changes
LGTM

2022-06-02 17:32 UTC, merged