process: update PR template to include release notes
apache/druid pull request #13188
Opened 2022-10-05 22:54 UTC by 317brian

### Description

* Updates the PR template to include a release notes section and a checkbox at the end
* Updates CONTRIBUTING.MD to include release notes tips and examples 

Followup work for this will include a PR to create a file in the repo to collect and copyedit the release notes from PRs on an ongoing basis to prepare for the next release. (I'll also need to do some catch up work for the existing PRs/commits that were added before this change gets implemented.)

We can add a stub file in this PR and direct people to add to it directly in lieu of them adding it to the PR description. But I think having people add it to the PR description would cause less friction based on how Druid release notes are currently oragnized.

<hr>

This PR has:
- [X] been self-reviewed.

2022-10-05 23:15 UTC, techdocsmith approved these changes
small nit. otherwise LGTM ✅

2022-10-05 23:15 UTC, techdocsmith commented on .github/pull_request_template.md
> +- [ ] a release note entry added to the PR description.
```suggestion
- [ ] a release note entry in the PR description.
```
nit

2022-10-06 03:11 UTC, clintropolis reviewed
:+1:

2022-10-06 03:11 UTC, clintropolis commented on .github/pull_request_template.md
> +For tips about how to write a good release note, see [Release notes](../CONTRIBUTING.md#release-notes).
the other links in the template are full links, I'm not certain if relative links work here or not, so to be safe we might want to make it match the others
```suggestion
For tips about how to write a good release note, see [Release notes](https://github.com/apache/druid/blob/master/CONTRIBUTING.md#release-notes).
```

2022-10-06 15:45 UTC, paul-rogers requested changes
@317brian, thanks for writing this up! It will be quite helpful to both developers and (I hope) doc writers.

2022-10-06 15:45 UTC, paul-rogers commented on CONTRIBUTING.md
> +When you contribute a change, we want to make sure Druid users learn about the change. Give it your best shot! Druid committers will review them as part of the release process.
Perhaps:

> Release notes are the way that Druid users will learn of your fix or improvement. What does a user need to know? Druid committers will review and edit your notes. The key is to identify the user impact.

2022-10-06 15:45 UTC, paul-rogers commented on CONTRIBUTING.md
> +**Summarize your change.** Describe the user impacting parts of your change, but try to be as concise as you can.
Perhaps add:

> A change is user impacting if it:
>
> * Changes what the user sees in the UI.
> * Changes any action that the user takes (in the UI, in the API, in configuration, in install, etc.)
> * Changes the results of any query, ingestion or task.
> * Changes performance (preferably making things faster).
> * Adds or deprecates features.
> * Anything else that changes install, configuration or operation of Druid.

2022-10-06 15:45 UTC, paul-rogers commented on CONTRIBUTING.md
> +| Deprecated: Removed / Will remove X. | Deprecated: Support for ZooKeeper X.Y will be removed in the next release, so consider upgrading ZooKeeper.         |
These are all great examples. The one item that might be missing is whether the user needs to do anything. For example, on that first one:

> New: You can now upload CSV files with a single header row for batch ingestion. Set the `infrerSchemaFromHeader` property of your Ingestion spec to `true` to enable this feature. See [doc link needed] for the details.

2022-10-07 16:24 UTC, paul-rogers approved these changes
@317brian, thanks for this improvement. LGTM.

2022-10-11 02:29 UTC, merged