Web console: add arrayOfDoublesSketch and other small fixes
apache/druid pull request #13486
Opened 2022-12-03 00:19 UTC by vogievetsky

This PR improves some small things in the console:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/177816/205412197-61cc4983-9e00-4c6c-b31b-9f564f4b920a.png">

- Support arrayOfDoubles sketch from the data loader (see https://apachedruidworkspace.slack.com/archives/C0303FDCZEZ/p1669826056035669) also improve the docs which were hard to read
- Fix padding if aggregating in a table
- Add syntax highlighting for window function keywords (see https://github.com/apache/druid/pull/13458)

2022-12-03 00:57 UTC, techdocsmith requested changes
Left some some suggestions

2022-12-03 00:57 UTC, techdocsmith commented on docs/development/extensions-core/datasketches-tuple.md
> +|metricColumns|If building sketches from raw data, an array of names of the input columns containing numeric values to be associated with each distinct key. If not provided `filedName` is assumed to
```suggestion
|metricColumns|When building sketches from raw data, an array input column that contain numeric values to associate with each distinct key. If not provided, assumes `fieldName` is an `arrayOfDoublesSketch`|no, if not provided `fieldName` is assumed to be an arrayOfDoublesSketch|
```

2022-12-03 00:57 UTC, techdocsmith commented on docs/development/extensions-core/datasketches-tuple.md
> +- directly on top of an ArrayOfDoubles sketch - `metricColumns` is unset and `fieldName` represents an ArrayOfDoubles sketch (base64 encoded if at ingestion time) with `numberOfValues` doubles.
```suggestion
You can use the `arrayOfDoublesSketch` aggregator to:

- Build sketches from raw data. In this case, set `metricColumns` to an array.
- Build a sketch from an existing ArrayOfDoubles sketch . In this case, leave metricColumns` is unset and set the `fieldName` to an `ArrayOfDoubles` sketch with `numberOfValues` doubles. At ingestion time, you must base64 encode `ArrayOfDoubles`  sketches at ingestion time.
```

2022-12-03 00:57 UTC, techdocsmith commented on docs/development/extensions-core/datasketches-tuple.md
> +Compute a theta of unique users, for each user store the `added` and `deleted` scoers
```suggestion
Compute a theta of unique users. For each user store the `added` and `deleted` scores in a column called `users_theta`.
```
typo?

2022-12-03 00:57 UTC, techdocsmith commented on docs/development/extensions-core/datasketches-tuple.md
>  |name|A String for the output (result) name of the calculation.|yes|
```suggestion
|name|String representing the output column to store sketch values.|yes|
```
This is the destination column for the sketch, no?

2022-12-03 00:57 UTC, techdocsmith commented on docs/development/extensions-core/datasketches-tuple.md
> +Ingest a sketch column called `user_sketches` that has two doubles in its array.
```suggestion
Ingest a sketch column called `user_sketches` that has a base-64 encoded value of two doubles in its array and store it in a column called `users_theta`.
```

2022-12-05 09:28 UTC, petermarshallio commented on docs/development/extensions-core/datasketches-tuple.md
> +- directly on top of an ArrayOfDoubles sketch - `metricColumns` is unset and `fieldName` represents an ArrayOfDoubles sketch (base64 encoded if at ingestion time) with `numberOfValues` doubles.
Nit - "leave `metricsColumns` unset`

2022-12-07 03:37 UTC, clintropolis approved these changes

2022-12-07 05:21 UTC, merged