Fix value of lookup sync period in docs
apache/druid pull request #13695
Opened 2023-01-19 06:42 UTC by kfaraz

# Changes
- Update value of `druid.manager.lookups.period` in docs to `120_000`, which is the value used in `LookupCoordinatorManagerConfig`
- Remove statements that are not pertinent anymore

2023-01-25 20:33 UTC, techdocsmith requested changes
@kfaraz request some small stylistic changes

2023-01-25 20:33 UTC, techdocsmith commented on docs/configuration/index.md
> +These configuration options control the lookup management done by the coordinator. Configurations that affect propagation of lookups can be found in [dynamic configuration for lookups](../querying/lo
```suggestion
These configuration options control Coordinator lookup management. See [dynamic configuration for lookups](../querying/lookups.md#dynamic-configuration) configurations that affect lookup propagation.
```

2023-01-25 20:33 UTC, techdocsmith commented on docs/configuration/index.md
> +|`druid.manager.lookups.period`|How many milliseconds between checks for configuration changes|120000 (2 mins)|
```suggestion
|`druid.manager.lookups.period`|Number of milliseconds between checks for configuration changes|120000 (2 minutes)|
```

2023-01-31 04:18 UTC, kfaraz commented
Thanks for the review, @techdocsmith !

2023-02-02 02:11 UTC, techdocsmith approved these changes
LGTM

2023-02-02 02:12 UTC, merged