Input source security
apache/druid pull request #13989
Opened 2023-03-28 05:56 UTC by zachjsh

Fixes #XXXX.

### Description

#### Fixed the bug ...
#### Renamed the class ...
#### Added a forbidden-apis entry ...

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

<hr>

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

2023-03-28 18:00 UTC, zachjsh commented on sql/src/main/java/org/apache/druid/sql/calcite/external/ExternalTableMacro.java
Can this class be removed? Doesn't seem to be used anywhere.

2023-03-28 20:43 UTC, paul-rogers requested changes
Thanks for tackling this task!

2023-03-28 20:43 UTC, paul-rogers commented on extensions-core/s3-extensions/src/test/java/org/apache/druid/catalog/model/table/S3InputSourceDefnTest.java
> +    assertEquals(Collections.singleton(S3StorageDruidModule.SCHEME), externSpec.inputSourceTypes);
While this is OK, it muddies the semantics. There should be only one input source type, not a list. Yes, a list with one item is the same as a single value, but the list suggests that there could be more values, which there cannot be.

Second, the input source type should be the value returned from `typeValue()` that happens to be the same as the `SCHEME` constant, but that is an implementation detail.

Actually, the core problem here may be the lack of a `TYPE_KEY` constant in `S3InputSourceDefn`. Go ahead and add one, then use it here:

```java
public class S3InputSourceDefn extends FormattedInputSourceDefn
{
  public static final String TYPE_KEY = S3StorageDruidModule.SCHEME;
...

  @Override
  public String typeValue()
  {
    return TYPE_KEY;
  }
`

2023-03-28 20:43 UTC, paul-rogers commented on server/src/main/java/org/apache/druid/catalog/model/table/BaseInputSourceDefn.java
> +        Collections.singleton(typeValue())
Again, there can only ever be a single value.

2023-03-28 20:43 UTC, paul-rogers commented on server/src/main/java/org/apache/druid/catalog/model/table/ExternalTableSpec.java
> +  public final Set<String> inputSourceTypes;
Again, there can only ever be a single value.

2023-03-28 20:43 UTC, paul-rogers commented on server/src/main/java/org/apache/druid/server/security/AuthConfig.java
> +  private final boolean inputSourceTypeSecurityEnabled;
Maybe `enableInputSourceSecurity` shorter. Starts with a verb.

2023-03-28 20:43 UTC, paul-rogers commented on sql/src/main/java/org/apache/druid/sql/calcite/external/DruidExternTableMacro.java
> +    throw new RuntimeException("inputSource paramter not found in extern function");
paramter -> parameter

2023-03-28 20:43 UTC, paul-rogers commented on sql/src/main/java/org/apache/druid/sql/calcite/external/ExternalTableMacro.java
Please remove it if it is not used.

2023-03-28 20:43 UTC, paul-rogers commented on sql/src/main/java/org/apache/druid/sql/calcite/external/Externals.java
> +      Set<String> inputSourceTypes
There will only ever be one input source type.

2023-03-28 20:43 UTC, paul-rogers commented on sql/src/test/java/org/apache/druid/sql/calcite/CalciteInsertDmlTest.java
> +        .expectLogicalPlanFrom("insertFromExternal")
Should we include a test in which authorization fails?

2023-03-28 23:51 UTC, paul-rogers approved these changes
LGTM.

A couple of nits, and ensure there is a clean build, else +1.

2023-03-28 23:51 UTC, paul-rogers commented on extensions-core/s3-extensions/src/test/java/org/apache/druid/catalog/model/table/S3InputSourceDefnTest.java
> +    ExternalTableSpec externSpec = fn.apply("x", args, COLUMNS, mapper);;
Nit: extra semicolon. Here and below. A static check probably complained.

2023-03-29 20:01 UTC, abhishekrb19 reviewed
LGTM. Just a few minor suggestions. Thanks!

2023-03-30 02:15 UTC, merged

2023-03-30 02:16 UTC, zachjsh commented
thanks @abhishekrb19 ! I will take care of the minor comments in follow up pr.