Improve streaming ingestion completion timeout error message
apache/druid pull request #14636
Opened 2023-07-21 09:18 UTC by AmatyaAvadhanula

A streaming ingestion supervisor spec has the property: `completionTimeout` (defaults to 30 minutes), which is the total time to wait after the taskDuration has elapsed for the tasks to stop reading, create segments from intermediate persists, publish segments to deep storage, and finally hand them off from the peons to the historicals.

A task fails if the above operations are not completed before the completionTimeout has elapsed.

This PR adds steps for better debugging when such failures occur.

2023-07-21 11:01 UTC, kfaraz commented on indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java
> +                + "as well as the total time taken for segment handoff to the historicals.",
```suggestion
                + "Check metrics to see if the creation, publish or handoff of any segment is taking longer than usual.",
```

2023-07-21 11:42 UTC, kfaraz commented on indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java
> +                + "than usual.",
Nit: break the line sooner
```suggestion
                + "Check metrics and logs to see if the creation, publish or handoff"
                + "  of any segment is taking longer than usual.",
```

2023-07-26 03:00 UTC, asdf2014 requested changes

2023-07-26 03:00 UTC, asdf2014 commented on indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java
> +                + "  of any segment is taking longer than usual.",
nit: remove the extra blank char

2023-07-27 09:34 UTC, asdf2014 approved these changes

2023-08-22 09:03 UTC, AmatyaAvadhanula commented
@kfaraz, @asdf2014 Thank you for the review!

2023-08-22 09:03 UTC, merged