Code Coverage additions for Extensions
apache/druid pull request #17596
Opened 2024-12-30 23:52 UTC by ashwintumma23

### Description
* Contributes to code coverage for a few class in the `extensions-core` and `extensions-contrib` directories

#### Release note

<hr>

##### Key changed/added classes in this PR
* Prometheus Emitter 
  * `extensions-contrib/prometheus-emitter/src/test/java/org/apache/druid/emitter/prometheus/PrometheusEmitterConfigTest.java`
  * `extensions-contrib/prometheus-emitter/src/test/java/org/apache/druid/emitter/prometheus/PrometheusEmitterTest.java`
* Multi-Stage Query 
  * New: `extensions-core/multi-stage-query/src/test/java/org/apache/druid/msq/indexing/MSQTaskListTest.java`
  * `extensions-core/multi-stage-query/src/test/java/org/apache/druid/msq/indexing/MSQTuningConfigTest.java`
 * Simple Client SSLContext 
   * New: `extensions-core/simple-client-sslcontext/pom.xml`
   * New: `extensions-core/simple-client-sslcontext/src/test/java/org/apache/druid/https/SSLClientConfigTest.java`
   * New: `extensions-core/simple-client-sslcontext/src/test/java/org/apache/druid/https/SSLContextProviderTest.java`

<hr>

This PR has:

- [X] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [X] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

2025-01-06 05:19 UTC, kfaraz reviewed
Left some suggestions.

2025-01-06 05:19 UTC, kfaraz commented on extensions-core/simple-client-sslcontext/src/test/java/org/apache/druid/https/SSLContextProviderTest.java
> +  private SSLClientConfig mockConfig;
Why not create a concrete object instead of using a mock?

2025-01-06 05:19 UTC, kfaraz commented on extensions-core/simple-client-sslcontext/src/test/java/org/apache/druid/https/SSLClientConfigTest.java
> +    // Use reflection to set the private fields
Please don't use reflection for this.
Either
- add a constructor
- OR, override the getters to return the expected values
- OR, deserialize the object from a json string

2025-01-06 05:19 UTC, kfaraz commented on extensions-core/multi-stage-query/src/test/java/org/apache/druid/msq/indexing/MSQTuningConfigTest.java
> +  public void testToString()
Do we really need to test the `toString` method? AFAICT, the `toString` of this class is used only for debug logging.

2025-01-06 05:19 UTC, kfaraz commented on extensions-core/multi-stage-query/src/test/java/org/apache/druid/msq/indexing/MSQTaskListTest.java
> +  public void testToString()
Probably not needed.

2025-01-13 20:20 UTC, ashwintumma23 commented on extensions-core/simple-client-sslcontext/src/test/java/org/apache/druid/https/SSLClientConfigTest.java
> +    // Use reflection to set the private fields
Picked up the second option here to override the getters to return the expected values. Pushing changes in the next commit.

2025-01-13 20:23 UTC, ashwintumma23 commented on extensions-core/multi-stage-query/src/test/java/org/apache/druid/msq/indexing/MSQTaskListTest.java
> +  public void testToString()
Sounds good, removing in the next commit.

2025-01-13 20:23 UTC, ashwintumma23 commented on extensions-core/multi-stage-query/src/test/java/org/apache/druid/msq/indexing/MSQTuningConfigTest.java
> +  public void testToString()
Sounds good, removing in the next commit.

2025-01-13 23:35 UTC, ashwintumma23 commented on extensions-core/simple-client-sslcontext/src/test/java/org/apache/druid/https/SSLContextProviderTest.java
> +  private SSLClientConfig mockConfig;
Wanted to keep this in sync with `SSLClientConfigTest`, and then verify the getters are getting called. On another note, I think these tests are testing `SSLClientConfig` getters that are already tested in its own test class; so we can remove them.

2025-01-23 21:30 UTC, ashwintumma23 commented on extensions-core/simple-client-sslcontext/src/test/java/org/apache/druid/https/SSLContextProviderTest.java
> +  private SSLClientConfig mockConfig;
Removing the test entirely in the next commit, as it is not increasing functional coverage.

2025-01-24 13:08 UTC, kfaraz requested changes
Thanks for contributing to Druid, @ashwintumma23 !

I have left some suggestions. Let me know what you think.

As a general principle, while verifying getters, equals and hashCode of POJOs does help with code coverage, it doesn't always add a lot of value by itself. Moreover, these code paths tend to get covered anyway through functional tests where these POJOs are used.

So, I would advise focusing more on functionality when writing future tests.
I look forward to more contributions from you 🙂 .

2025-01-24 19:35 UTC, ashwintumma23 commented on extensions-core/multi-stage-query/src/test/java/org/apache/druid/msq/indexing/MSQTaskListTest.java
> +
Makes sense. Removed the tests in the next commit.

2025-01-24 19:36 UTC, ashwintumma23 commented on extensions-core/simple-client-sslcontext/src/test/java/org/apache/druid/https/SSLClientConfigTest.java
> +  public void testGetters()
Makes sense. Removing the tests in the next commit.

2025-01-24 21:42 UTC, ashwintumma23 commented on extensions-contrib/prometheus-emitter/src/test/java/org/apache/druid/emitter/prometheus/PrometheusEmitterConfigTest.java
> +  }
Also combined these two tests into one, so that both ExporterStrategy and PushGatewayStrategy will have one test each.

2025-01-29 23:05 UTC, ashwintumma23 commented on extensions-contrib/prometheus-emitter/src/test/java/org/apache/druid/emitter/prometheus/PrometheusEmitterConfigTest.java
> +  public void testNegativeWaitForShutdownDelay()
Done, verified the exception message as well. Pushed in the commit.

2025-02-06 04:25 UTC, kfaraz approved these changes

2025-02-06 04:26 UTC, merged